# Generated by Django 3.2.15 on 2022-08-21 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='upload',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='casteCertificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='casteCertificateimages/'),
            preserve_default=False,
        ),
    ]
