# Generated by Django 4.0.6 on 2022-08-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
