# Generated by Django 3.2.15 on 2022-08-21 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20220821_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='existingCaste',
            new_name='Caste',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='existingSubCaste',
            new_name='SubCaste',
        ),
        migrations.AddField(
            model_name='customuser',
            name='havesafaiKarmchari',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='safaiKarmchariCertificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='safaiKarmchariCertificateimages/'),
            preserve_default=False,
        ),
    ]
