# Generated by Django 3.2.15 on 2022-08-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20220821_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Caste',
            new_name='CasteName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='SubCaste',
            new_name='SubCasteName',
        ),
    ]
