# Generated by Django 4.0.6 on 2022-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_otherinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('otpVerifyed', models.BooleanField(default=False)),
            ],
        ),
    ]
