# Generated by Django 3.2.15 on 2022-08-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20220821_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='casteCertificate',
            new_name='casteCertificateimage',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='safaiKarmchariCertificate',
            new_name='safaiKarmchariCertificateimage',
        ),
    ]
