# Generated by Django 3.2.15 on 2022-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20220821_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='casteCertificateimage',
            field=models.FileField(blank=True, null=True, upload_to='casteCertificateimages/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='safaiKarmchariCertificateimage',
            field=models.FileField(blank=True, null=True, upload_to='safaiKarmchariCertificateimages/'),
        ),
    ]
