# Generated by Django 3.2.15 on 2022-08-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20220821_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadharLastDigits',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
