# Generated by Django 3.2.15 on 2022-08-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_customuser_aadharlastdigits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='havesafaiKarmchari',
            new_name='havesafaiKarmchariId',
        ),
    ]
