# Generated by Django 3.2.15 on 2022-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20220822_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departmenName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
