# Generated by Django 3.2.15 on 2022-08-22 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20220822_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dmDistrict',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
