# Generated by Django 3.2.15 on 2022-08-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20220822_1100'),
    ]

    operations = [
       
    ]
