# Generated by Django 3.2.15 on 2022-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_customuser_rmdistricts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rmDistricts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
