# Generated by Django 3.2.15 on 2022-08-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_customuser_rmdistricts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinformation',
            old_name='user',
            new_name='Bankuser',
        ),
        migrations.RenameField(
            model_name='eligibilityinfo',
            old_name='user',
            new_name='Eligibiltyuser',
        ),
        migrations.RenameField(
            model_name='incomeanddomicileinfo',
            old_name='user',
            new_name='Incomeuser',
        ),
        migrations.RenameField(
            model_name='otherinfo',
            old_name='user',
            new_name='Otheruser',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='user',
            new_name='Personaluser',
        ),
        migrations.RenameField(
            model_name='qualificationinfo',
            old_name='user',
            new_name='Qualificationuser',
        ),
        migrations.RenameField(
            model_name='residentialinfo',
            old_name='user',
            new_name='Residentialuser',
        ),
        migrations.RenameField(
            model_name='schemedetails',
            old_name='user',
            new_name='Schemeuser',
        ),
    ]
