# Generated by Django 3.2.15 on 2022-08-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20220822_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinformation',
            old_name='Bankuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='eligibilityinfo',
            old_name='Eligibiltyuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='incomeanddomicileinfo',
            old_name='Incomeuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='otherinfo',
            old_name='Otheruser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='Personaluser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='qualificationinfo',
            old_name='Qualificationuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='residentialinfo',
            old_name='Residentialuser',
            new_name='user',
        ),
    ]
