# Generated by Django 3.2.15 on 2022-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20220822_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemedetails',
            old_name='Schemeuser',
            new_name='user',
        ),
    ]
