# Generated by Django 3.2.15 on 2022-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_rename_schemeuser_schemedetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='subCaste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
